language: emacs-lisp

matrix:
  fast_finish: true

before_install:
  - sudo apt-key adv --keyserver pgp.mit.edu --recv-keys 3FA7E0328081BFF6A14DA29AA6A19B38D3D831EF
  - sudo sh -c "echo 'deb http://download.mono-project.com/repo/debian wheezy main' >> /etc/apt/sources.list.d/mono-xamarin.list"
  - sudo sh -c "echo 'deb http://download.mono-project.com/repo/debian wheezy-libtiff-compat main' >> /etc/apt/sources.list.d/mono-xamarin.list"
  - sudo add-apt-repository -y ppa:cassou/emacs
  - sudo apt-get update -qq

install:
  - sudo apt-get install -yq emacs24 emacs24-el emacs24-common-non-dfsg
  - sudo apt-get install -yq mono-complete nuget
  - sudo apt-get install -yq fsharp

script:
  - FSharp.AutoComplete/fake Test

