environment:
  EMACSBIN: emacs-24.4-bin-i686-mingw32.7z
  FSharpBinding_BlockingTimeout: 1000
  FSharpBinding_MaxTimeout: 10000
matrix:
  fast_finish: true
install:
  - ps: Start-FileDownload "http://downloads.sourceforge.net/project/emacs-bin/releases/$env:EMACSBIN"
  - ps: 7z x $env:EMACSBIN -oemacs-local | FIND /V "ing  "
build_script:
  - cmd: FSharp.AutoComplete\fake.cmd Test
test: off
